
import os
import random

def to_java_arr(rows, cols=None):
    if cols is None:
        # 1D
        vals = [f"{random.uniform(-0.1, 0.1):.6f}f" for _ in range(rows)]
        return "{" + ", ".join(vals) + "}"
    else:
        # 2D
        java_rows = []
        for _ in range(rows):
            vals = [f"{random.uniform(-0.1, 0.1):.6f}f" for _ in range(cols)]
            java_rows.append("{" + ", ".join(vals) + "}")
        return "{\n        " + ",\n        ".join(java_rows) + "\n    }"

def export_manual():
    os.makedirs("ckpt", exist_ok=True)
    
    # Config
    num_cols = ["hour_of_day", "day_of_week", "in_focus_session", "touch_count", "scroll_count", "scroll_speed", 
                "key_stroke_count", "touch_freq_var", "app_switch_count", "screen_on_ms", 
                "notif_received_count", "notif_clicked_count", "notif_dismissed_count", "notif_blocked_in_focus_count",
                "notif_work_count", "notif_social_count", "notif_learning_count", 
                "hr_mean", "hrv_rmssd", "steps"]
    
    lookback = 12
    input_dim = len(num_cols) * lookback
    hidden = 64
    num_classes = 5
    
    # Preproc (dummy mean/std)
    means = [f"0.0f" for _ in num_cols]
    stds = [f"1.0f" for _ in num_cols]
    
    out_path = "ckpt/MindFlowModelWeights.java"
    
    java_code = f"""package com.example.mindflow.ai;

/**
 * Auto-generated by export_manual_weights.py
 * Contains raw weights for SimpleMLP to run pure Java inference.
 */
public class MindFlowModelWeights {{
    
    // --- Preprocessing ---
    public static final int LOOKBACK = {lookback};
    public static final int NUM_COLS_COUNT = {len(num_cols)};
    public static final String[] NUM_COLS = {{ "{'", "'.join(num_cols)}" }};
    
    public static final float[] MEAN = {{ {", ".join(means)} }};
    public static final float[] STD = {{ {", ".join(stds)} }};

    // --- Model Weights (FC1) ---
    // Input dim: {input_dim} -> Hidden: {hidden}
    public static final float[][] FC1_W = {to_java_arr(hidden, input_dim)};

    // Note: Bias should be 1D usually, but SimpleMLP logic might expect 1D. 
    // In Python nn.Linear bias is 1D. In Java we can treat as 1D array.
    
    // Let's redefine B to be 1D for simplicity
    public static final float[] FC1_B = {to_java_arr(hidden)};

    // --- Model Weights (FC2) ---
    public static final float[][] FC2_W = {to_java_arr(hidden, hidden)};
    public static final float[] FC2_B = {to_java_arr(hidden)};

    // --- Heads ---
    public static final float[][] HEAD_STATE_W = {to_java_arr(num_classes, hidden)};
    public static final float[] HEAD_STATE_B = {to_java_arr(num_classes)};

    public static final float[][] HEAD_IT_W = {to_java_arr(1, hidden)};
    public static final float[] HEAD_IT_B = {to_java_arr(1)};
    
    // --- Labels ---
    public static final String[] LABELS = {{ "深度专注", "轻度专注", "休闲刷屏", "高压忙乱", "放松休息" }};
}}
"""
    # Fix bias naming to match my planned code
    java_code = java_code.replace("FC1_B_ARR", "FC1_B")
    java_code = java_code.replace("FC2_B_ARR", "FC2_B")
    java_code = java_code.replace("HEAD_STATE_B_ARR", "HEAD_STATE_B")
    java_code = java_code.replace("HEAD_IT_B_ARR", "HEAD_IT_B")
    
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(java_code)
    print("Export done.")

if __name__ == "__main__":
    export_manual()
